### ISSUE TITLE
Support extension types

### ISSUE THREAD

**Issue by dbohdan** [jdc8/msgpack#4]
Thanks for merging my PR so quickly!

Version 5 of the MessagePack spec supports [extensions](https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family) (custom data types), including one that is optional but standardized: timestamp.  Currently this package decodes MessagePack data with extensions incorrectly.  It shouldn't, and it would be nice to support timestamps.  I plan to address this next.

**Comment by jdc8** [comment]
I stopped using the msgpack some time ago, project requirements changed ...
